# Lecture 13 - Classes

## Object (variable) Method (function)

In this lecture we will learn classes and the basics of object oriented programming. It's important to know the main idea and be able to write simple classes that serve basic mathematical purposes.

This will explain expressions like `x.append(5)` that we used for lists and `arr.reshape(4,-1)` for numpy arrays. 

## Review

In [1]:
import numpy as np
arr = np.arange(10)
print(arr.reshape(2,-1))
print()
print(np.reshape(arr, [2, -1]))

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]]


The main idea of classes is that sometimes you want to put various pieces of data, and functions that manipulate the data in one place. The functions are called *methods* of the class. 

For example, a vector in $\mathbb{R}^3$ is represented by three floats. So why not make a new data type that contains three floats and call it a vector?

Actually, let's make a list of all the things we know we can do to vectors in $\mathbb{R}^3$. We can:

* Have x, y, z variables for the three coordinates,
* take the length of a vector (a.k.a., norm),
* we can normalize the vector, meaning we can divide it by the norm so that it now has the same direction but has length 1,
* take dot product of two vectors, i.e. take $(x_1,y_1,z_1)\cdot(x_2,y_2,z_2) = x_1x2 + y_1y_2 + z_1z_2$,
* add vectors,
* multiply a vector by a scalar
* take cross product of two vectors

We will make a new type of object in Python, called Vector, that allows us to do all of these things. 


In [ ]:
import math
class Vector():
    
    # initialize the vector, we will say   
    # v = Vector(1,2,3)
    # to get a new vector with those coordinated
    def __init__(self, xx, yy, zz):
        self.x = xx
        self.y = yy
        self.z = zz
    
    # compute the norm
    def norm(self):
        return math.sqrt(self.x*self.x + self.y*self.y + self.z*self.z)

    # divide by the norm
    def normalize(self):
        no = self.norm()
        self.x /= no
        self.y /= no
        self.z /= no    
        
# note that every function has self in it, so that it can access the information of the class

The `class` specifies what constitutes an object (the variables in it, which are all the variables that appear as `self.---`), and the functions that can be used. To create an object of the class, a.k.a. an instance of the class, we need to call the name of the class as if it's a function. 

In [ ]:
v = Vector(1.0,2.0,3.0)   
# the arguments of this call must match the arguments of the __init__ 
# function in the class, except the self part

In [ ]:
type(v)

In [ ]:
print(v.x)
print(v.y)
print(v.z)

In [ ]:
v.normalize()
print(v.x, v.y, v.z)

In [ ]:
print(v)

#### What happened?
`print`  gives us something that tells you that `v` is a
vector at some memory location. Whenever we invoke Python's `print` command, it first applies the Python `repr` function to the item you are printing. The `repr` returns a string containing a printable
version of the object you are printing. We can customize this behavior by adding the `__repr__(self)` function in this class.

In [ ]:
import math
class Vector():
    
    def __init__(self, xx, yy, zz):
        self.x = xx
        self.y = yy
        self.z = zz
    
    def norm(self):
        return math.sqrt(self.x*self.x + self.y*self.y + self.z*self.z)

    def normalize(self):
        no = self.norm()
        self.x /= no
        self.y /= no
        self.z /= no    
    
    def __repr__(self):
        return "<" + str(self.x)[:5] + " , " + str(self.y)[:5] + " , " + str(self.z)[:5] + ">"
    
# note that every function has self in it, so that it can access the information of the class

In [ ]:
v = Vector(1.0,2.00000001,3.04383)

In [ ]:
print(v) # a little buggy if we just display using 5 chacracters

This should remind of how we used `xs.append(5)` for a list xs. Indeed, `list` is a class just like our `Vector` class, and there is a function called `append(self, x)` in it that adds an extra element. 

Let's also add dot products, scalar multiplication:

In [ ]:
import math
class Vector():
    
    def __init__(self, xx, yy, zz):
        self.x = xx
        self.y = yy
        self.z = zz
    
    def norm(self):
        return math.sqrt(self.x*self.x + self.y*self.y + self.z*self.z)

    def normalize(self):
        no = self.norm()
        self.x /= no
        self.y /= no
        self.z /= no    
    
    def __repr__(self):
        return "<" + str(self.x) + " , " + str(self.y) + " , " + str(self.z) + ">"
    
    def dot(self, w):
        return self.x * w.x + self.y * w.y + self.z * w.z
    
    # returns a new vector without modifying the original
    def times_scalar(self, alpha):
        return Vector(alpha * self.x, alpha * self.y, alpha * self.z)
        
# note that every function has self in it, so that it can access the information of the class

In [ ]:
Vector(1.0,2.0,3.0).dot(Vector(1.0,1.0,1.0))

In [ ]:
Vector(1.0,2.0,3.0).times_scalar(3)

In [ ]:
(Vector(1.0, 2.0, 3.0) + Vector(0.0, 5.0, 10.0)) # this gives us error...what?

We can also write addition of vectors, we could write `add(self,w)` in the class and use `v.add(w)` to add `v` and `w`, but we could also **overload** the `+` operator as follows:

In [ ]:
import math
class Vector():
    
    def __init__(self, xx, yy, zz):
        self.x = xx
        self.y = yy
        self.z = zz
    
    def norm(self):
        return math.sqrt(self.x*self.x + self.y*self.y + self.z*self.z)

    def normalize(self):
        no = self.norm()
        self.x /= no
        self.y /= no
        self.z /= no    
    
    def __repr__(self):
        return "<" + str(self.x) + " , " + str(self.y) + " , " + str(self.z) + ">"
    
    def dot(self, w):
        return self.x * w.x + self.y * w.y + self.z * w.z
    
    def __add__(self, w):
        return Vector(self.x + w.x, self.y + w.y, self.z + w.z)
    
# note that every function has self in it, so that it can access the information of the class

In [ ]:
(Vector(1.0, 2.0, 3.0) + Vector(0.0, 5.0, 10.0))

## Exercise 1:
Create a method (function) for `Vector` class that computes the cross product of a vector with another.

## Exercise 2:

Create a class called `Line` which represents a line with equation $ax + by + c = 0$. Write the `__init__(self,a,b,c)`, `__repr__(self)` and `intersect(self,other_line)` methods for the class. The intersect method should return the coordinates of the intersection point of two lines. 


## Exercise 3: subclasses
Creating a class `Die` simulating rolling a die, then we can create subclasses by using the object and methods in class `Die`.
For example, we can simulate the game called ["Craps" (...who came up with this name)](http://mathworld.wolfram.com/Craps.html), using the following code.

In [ ]:
class Die(object):
    # Simulate a 6-sided die.
    def __init__( self ):
        self.domain= range(1,7)
    def roll( self ):
        self.value= random.choice(self.domain)
        return self.value
    def getValue( self ):
        return self.value

class Dice( object ):
    # Simulate a pair of dice.
    def __init__( self ):
        # Create the two Die objects.
        self.myDice = [ Die(), Die() ]
    def roll( self ):
        # Return a random roll of the dice.
        for d in self.myDice:
            d.roll()
    def getTotal( self ):
        # Return the total of two dice.
        return self.myDice[0].value + self.myDice[1].value
    def getTuple( self ):
        # Return a list of the dice rolls.
        return self.myDice

class CrapsDice( Dice ):
    # Extends Dice to add features specific to Craps.
    def hardways( self ):
        # Returns True if this was a hardways roll?
        return self.myDice[0].value == self.myDice[1].value
    def isPoint( self, value ):
        # Returns True if this roll has the given total
        return self.getTotal() == value

## A hard exercise for veterans:
Can you vectorized above class for "Craps" so it can include objects like simulations of a sequence of dice rolls, winning rate, and standard deviation of the winning.