# Lecture 6

* advanced technique for `for` loops
* using these loops for `list` and `array` to computer vector-vector, matrix-vector products
* some built-in functions in NumPy


## Some review on `FOR` loops

The most straightforward way to loop through a `list` or an `array`.

In [1]:
import numpy as np

In [2]:
# review: simpliest for loops
for x in [1,10,100,1000,12344]:
    print(x)

1
10
100
1000
12344


Easier and cleaner than `while` loops.

In [4]:
total = 0
for i in range(101):
    total += i
    print(total) # one trick to debug our code 
    # is to print the desired result at each iteration
print(total)

0
1
3
6
10
15
21
28
36
45
55
66
78
91
105
120
136
153
171
190
210
231
253
276
300
325
351
378
406
435
465
496
528
561
595
630
666
703
741
780
820
861
903
946
990
1035
1081
1128
1176
1225
1275
1326
1378
1431
1485
1540
1596
1653
1711
1770
1830
1891
1953
2016
2080
2145
2211
2278
2346
2415
2485
2556
2628
2701
2775
2850
2926
3003
3081
3160
3240
3321
3403
3486
3570
3655
3741
3828
3916
4005
4095
4186
4278
4371
4465
4560
4656
4753
4851
4950
5050
5050


`range(n)` starts from 0, what if we want to start from 1?

In [5]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
"%2d" %5
# 2 here means 2 spaces to display a variable
# d means decimal
# e means exponential

' 5'

In [12]:
"%d" %5.4

'5'

For the format of percent sign please refer to [http://infohost.nmt.edu/tcc/help/pubs/python25/web/str-format.html](http://infohost.nmt.edu/tcc/help/pubs/python25/web/str-format.html)

In [11]:
for i in range(1,10):
    print("%2d" %i)

 1
 2
 3
 4
 5
 6
 7
 8
 9


We can have nested loop as well: print a 9x9 multiplication table

In [16]:
for i in range(1,10):
    for j in range(1,10):
        print("%5d" %(i*j), end = " ") 
        # end = " " adds a space after each print
    print() # forcing a newline

    1     2     3     4     5     6     7     8     9 
    2     4     6     8    10    12    14    16    18 
    3     6     9    12    15    18    21    24    27 
    4     8    12    16    20    24    28    32    36 
    5    10    15    20    25    30    35    40    45 
    6    12    18    24    30    36    42    48    54 
    7    14    21    28    35    42    49    56    63 
    8    16    24    32    40    48    56    64    72 
    9    18    27    36    45    54    63    72    81 


How about a factorial $n = n\cdot (n-1)\cdot (n-2) \cdot \dots \cdot 2 \cdot 1$ for $n\geq 1$ and $n \in \mathbb{N}$?

In [17]:
def myfactorial(n):
    # enter code here
    prod = 1
    for i in range(1,n+1):
        prod *= i
        # same with prod = prod*i
    return prod    

In [22]:
myfactorial(5)

120

In [24]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
Aindex = np.arange(6).reshape(2,3)
print(Aindex)

[[0 1 2]
 [3 4 5]]


In [29]:
A = np.random.randint(10, 20, size = (2,3))
print(A)

[[19 12 12]
 [12 14 14]]


Iterate in the linear index of `A`

In [30]:
for x in np.nditer(A):
    print(x)

19
12
12
12
14
14


List the element of `A` using the linear index, same with above

In [31]:
for x in A.flat:
    print(x)

19
12
12
12
14
14


In [33]:
for i in Aindex.flat:
    print(i)

0
1
2
3
4
5


In [34]:
A

array([[19, 12, 12],
       [12, 14, 14]])

In [35]:
for x in np.nditer(A, order='F'): 
    # Fortran order, same with the order of MATLAB A(:)
    # for MATLAB users
    print(x)

19
12
12
14
12
14


### Some advanced technique manipulating ndarray (optional reading)

In [ ]:
for x in np.nditer(A, op_flags=['readwrite']):
    x[...] = 2*x

In [ ]:
print(A)

Iterating using the 2-d index of `A`

In [ ]:
for x, y in np.ndindex(A.shape):
    print((x,y))

## Vector-vector inner product
The inner product (or dot product): for $\mathbf{a}, \mathbf{b} \in \mathbb{R}^n$, their inner product is
$\mathbf{a}\cdot\mathbf{b} = \displaystyle\sum_{i=1}^n a_i b_i.$

In [40]:
# using for loop
def innerprod(a,b):
    #enter code here
    inner = 0 # initialize
    if len(a) == len(b):
        for i in range(len(a)):
            inner += a[i]*b[i]
            # inner = inner + a[i]*b[i]
        return inner
    else:
        print("Please enter vectors of equal length")

In [42]:
result = innerprod([1,2],[5,1])
result

Please enter vectors of equal length


In [44]:
arr1 = np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr2 = arr1[::-1]
arr2

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [49]:
arr1[:]*arr2[:] # not inner product
# * is element-wise product for nparray

array([ 0,  8, 14, 18, 20, 20, 18, 14,  8,  0])

In [50]:
arr1*arr2 # same with above if arr1 and arr2 are two vectors

array([ 0,  8, 14, 18, 20, 20, 18, 14,  8,  0])

In [51]:
sum(arr1*arr2)

120

In [ ]:
def innerprodarr(a,b):
    result = a[:]*b[:]
    result = sum(result)
    # this implementation is faster and better for numpy array

In [ ]:
# alternate way no.1
v=[1,2,3]
w=[5,6,7]
for x,y in zip(v,w):
    print([x,y])    

In [52]:
# alternate way no.2, there is a function for dot product in numpy
np.dot(arr1,arr2)

120

## Matrix vector multiplication
We have $\mathbf{A}\in \mathbb{R}^{m\times n}$ being a matrix, and $\mathbf{x}\in \mathbb{R}^n$ being a (column) vector. Then we can compute $\mathbf{A}\mathbf{x}$:
$$\mathbf {A} \mathbf{x}=
\begin{pmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}
\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\\\end{pmatrix}
\begin{pmatrix}x_{1}\\x_{2}\\\vdots \\x_{n}\end{pmatrix}
=
\begin{pmatrix}a_{11}x_{1}+\cdots +a_{1n}x_{n}\\a_{21}x_{1}+\cdots +a_{2n}x_{n}\\ \vdots \\a_{m1}x_{1}+\cdots +a_{mn}x_{n}\end{pmatrix}
= \begin{pmatrix} \mathbf{a}_1\cdot \mathbf{x} \\ \mathbf{a}_2\cdot \mathbf{x} \\ \vdots \\ 
\mathbf{a}_m\cdot \mathbf{x}\end{pmatrix}
$$
where the matrix $\mathbf {A} $ has the following representation:
$$\mathbf {A} = (\mathbf{a}_1 , \mathbf{a}_2 ,\cdots ,\mathbf{a}_m)^T, \quad \text{ with } \mathbf{a}_j = \text{the column vector representing $\mathbf{A}$'s $j$-th row} .$$

In [59]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A = np.array(range(1,10)).reshape(3,3) # same with above
x = np.array([1, 0, -1])
print("A = ", A)
print("x = ", x)

A =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
x =  [ 1  0 -1]


In [60]:
A*x # * is elementwise product

array([[ 1,  0, -3],
       [ 4,  0, -6],
       [ 7,  0, -9]])

In [61]:
np.multiply(A,x) # same with A*x, multiply arrays element-wise.

array([[ 1,  0, -3],
       [ 4,  0, -6],
       [ 7,  0, -9]])

In [9]:
# more example
S = np.arange(9).reshape(3,3)
v = np.arange(3)

In [10]:
np.multiply(S,v)

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16]])

#### Question: how to we implement the matrix vector multiplication?

In [62]:
prod = np.zeros(len(x)) # initialization
for i in range(len(x)):
    # what is here
    prod[i] = np.dot(A[i,:],x)
    # A's i-th row
print(prod)

[-2. -2. -2.]


In [63]:
def matvecmulti(A,x):
    # insert code here
    prod = np.zeros(len(x)) # initialization
    for i in range(len(x)):
        # what is here
        prod[i] = np.dot(A[i,:],x)
        # A's i-th row
    return prod

In [64]:
matvecmulti(A,x)

array([-2., -2., -2.])

In [65]:
np.matmul(A,x) # built-in function in numpy

array([-2, -2, -2])


----

<br><br>
## (Optional reading) A cool example using FOR and WHILE: *Collatz conjecture*

We can use lists together with loops to have lots of variables to keep track of things.

We are looking for the numbers with the longest sequences in the $3n+1$ problem.  

Recall that the $3n+1$ problem works as follows:

* Start with $a_0 = k$
* if $a_i$ is odd, let $a_{i+1} = 3a_i + 1$
* if $a_i$ is even, let $a_{i+1} = a_i/2$

If we start with $a_0 = 3$, the sequences is:
$3, 10, 5, 16, 8, 4, 2, 1$

If we start with $a_0 = 9$, the sequence is:
$9, 28, 14, 7, 22, 11, 34, 17, 52, 26, 13, 40, 20, 10 5, 16, 8, 4, 2, 1$

The funny thing that nobody understands why is that the sequence seems to always ends with 1. 

This is sometimes called the *Collatz conjecture* (xkcd's take):

![alt text](https://imgs.xkcd.com/comics/collatz_conjecture.png "The Strong Collatz Conjecture states that this holds for any set of obsessively-hand-applied rules")

----
Let's find the number $< 1000000$ with the longest sequence

In [ ]:
def collatzlist(a):
    lst = []
    if a<=0:
        # print('please enter a positive integer')
        return lst
    else:
        while a!=1:
            if a % 2 == 0:
                a = a // 2
            else:
                a = 3*a + 1
            lst.append(a)
        return lst

In [ ]:
collatzlist(9)

In [ ]:
def collatzlen(a):
    return len(collatzlist(a))

In [ ]:
collatzlen(9)

If we want to find an integer $<100$

In [ ]:
M = 100

max_len = -1
max_len_came_from = -1

for i in range(M):
    le = collatzlen(i)
    if le > max_len:
        max_len = le
        max_len_came_from = i
        
print("maximum sequence length is for the number", max_len_came_from, "and it is", max_len) 