# Lecture 4
In this lecture, we will to learn NumPy, which is the linear algebra package of python. NumPy `array` , and in the last part, we will learn how to use Matplotlib to draw the graph of a function.

## Review of NumPy array
`ndarray` is an arbitrary dimension set of variables of the **same type** (cf. `list` can be concatenate different types). In default, one entry of an array is a 64-bit float (a real number represented by 64 binary digit).

In [1]:
lst1 = [1, 'blah'] # we cannot do this for ndarray
print(lst1)

[1, 'blah']


In [2]:
# always run this cell block first
import numpy as np

In [8]:
lst = []
for i in range(10):
    lst.append(i)

In [9]:
print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
type(arr)

numpy.ndarray

In [12]:
arr[0]

0

**Remark**" `[]` is used for array indexing, `()` is used as input of functions

In [14]:
arr[-2] 

8

In [15]:
arr[4]

4

#### Slicing
We can use slicing `:` which is similar to `:` in MATLAB, which is a tricking to obtain certain indexed elements very fast. The syntax for slicing is to put `star:stop:step` as indices for an array, if there is no `step`, it is 1.

In [20]:
arr[0:1] # this operation generates an array

array([0])

In [21]:
arr[0]

0

In [22]:
arr[0:2] # the last element is the 2nd, not the third

array([0, 1])

In [23]:
arr[2]

2

----

In [24]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
arr.shape

(3, 4)

In Matlab, the following command should be `arr(1,:)` 

In [27]:
arr[1,:] # the second row

array([5, 6, 7, 8])

In [26]:
arr[0,:] # the first row of arr

array([1, 2, 3, 4])

In [28]:
arr[0:1, :] # this is the same with arr[0,:]

array([[1, 2, 3, 4]])

In [29]:
arr[:,0] # the first column

array([1, 5, 9])

#### Remark (please read in detail after lecture): 
Index `i`, returns the same values as `i:i+1`. In particular, a selection tuple with the $p$-th element an integer (and all other entries `:`) returns the corresponding sub-array with dimension $N - 1$. If $N = 1$ then the returned object is an array scalar.

If the selection tuple has all entries : except the $p$-th entry which is a slice object `i:j:k`, then the returned array has dimension $N$ formed by concatenating the sub-arrays returned by integer indexing of elements $i, i+k, ..., i + (m - 1) k < j$.

In [30]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
arr[1,:]

array([5, 6, 7, 8])

In [ ]:
arr[3,:] # this gives error b/c there is no 4th row

In [31]:
arr[1:3,1:3] # the second row, third row, and the second column, thid column

array([[ 6,  7],
       [10, 11]])

In [35]:
arr[1:2,1:2] # the second row, the second column

array([[6]])

In [37]:
arr[1:-1,:] # the second row, before the last row

array([[5, 6, 7, 8]])

In [39]:
# if we want to access the last row
arr[1:,:] # the second row to the last row

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr[0:-1,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

The indexing tricks above are enough for our class. For advanced slicing and indexing tricks, please refer to [https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html#advanced-indexing](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html#advanced-indexing)

#### nd-array
3 or more dimensional arrays too

In [40]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [41]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [42]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(arr2)

[[ 7  8  9]
 [10 11 12]]


In [43]:
arr3 = np.array([arr1,arr2]) # this gives us an extra dimension
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [44]:
arr3.shape  # in matlab it would be shape(arr3)

(2, 2, 3)

**Remark**: the order of the shape is from the outermost to the innermost.


In [ ]:
arr3[0,1,2]

### Building Arrays

In [46]:
arr = np.zeros(3) # 0. means 0.0, which is a float (cf. 0 is an int)
print(arr)

[0. 0. 0.]


In [48]:
# np.zeros[3,3] is a wrong syntax
arr = np.zeros([3,3])   # you put the shape in as a list
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
arr = np.zeros([3,3,2])
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [51]:
arr = np.empty([3,3]) # please check the help on np.empty()
arr

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.54937873e-321],
       [1.69121231e-306, 2.56761491e-312, 5.97819431e-322]])

The identity matrix, for example, $\begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0\\ 0 & 0 & 1\end{pmatrix}$

In [52]:
arr = np.identity(3)
arr # 1. means 1.0, which is a float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [56]:
arr = np.eye(4,k=1)
print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [57]:
arr = np.eye(4,k=-1)
print(arr)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


Equally distant points:

In [58]:
arr = np.arange(10) # this is not arrange!!!!
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [59]:
arr = np.arange(1,2,0.1) #0.1 is the gap between the points
print(arr) # be careful with the indexing!

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [60]:
# linspace means linear space
arr = np.linspace(1,2,11)   
# 11 is the number of points between 0 and and 1 (inclusive)
print(arr)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2. ]


**Remark (optional)**<br><br>
we could have done this with list comprehensions (`[1 + 0.1*x for x in range(11)]`) but anything you do in numpy will be faster. 

### Difference of lists vs numpy arrays
Let us see the following example:

In [61]:
np.array([1,2,3]) + np.array([4,5,6])  

array([5, 7, 9])

 Try the following code: if these were lists, it would be concatenation

In [62]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

It added the arrays as if they were vectors. Numpy figures out how to use the function with the array you gave. 

## (Actual lecture ends here)

----

### Reshape
Alternatively, maybe you want to control it youself by `reshape`:

In [ ]:
arr = np.array(range(16))

In [ ]:
arr.reshape(4,4)

In [ ]:
arr.reshape(2,2,-1)    # if you put -1, it figures out what the shape should be

In [ ]:
arr

In [ ]:
np.reshape(arr, (2,2,-1)) # -1 means unspecified

In [ ]:
np.sum(arr)

In [ ]:
np.mean(arr)

In [ ]:
np.apply_along_axis()

In [ ]:
np.apply_along_axis(np.sum, 0, arr)

In [ ]:
np.apply_along_axis(np.sum, 1, arr)

There is also: `np.apply_over_axes`, be aware of this plural `axes`.

In [ ]:
np.apply_over_axes(np.sum, arr, 0)

----

# Plotting with Matplotlib

This is very very similar to Matlab's plotting functions. The first line in the following cell calls the `inline` backend of `matplotlib`, which will embed plots inside the notebook;  `qt` will float outside this page.

In [ ]:
%matplotlib inline 
# default is inline

import matplotlib.pyplot as plt
import numpy as np


from math import pi # so that we can use pi directly instead of math.pi
from math import cos, sin

Say if we want to plot $y = \cos(x)$ and $y = \sin(x)$

In [ ]:
xs = np.linspace(0, 2*pi, 200)
cosxs = np.cos(xs)
sinxs = np.sin(xs)

In [ ]:
# plt is the pyplot function in the matplotlib module
# to connect the all the dots
%matplotlib qt
plt.plot(xs, cosxs)  # first one is blue
plt.plot(xs, sinxs)  # second one is orange

In [ ]:
# we could even annotate the graph we have
plt.plot(xs, cosxs, color = 'blue') 
plt.plot(xs, sinxs, color = 'red') 
plt.grid(True)
plt.axis('auto')
plt.annotate('local maximum of $sin(x)$', xy=(pi/2, 1), xytext=(3, 1.5), 
             arrowprops = dict(facecolor='black',shrink = 0.1))
plt.show() # suppress the output, similar to `drawnow` in MATLAB

To see more annotating style, please visit <a href="https://matplotlib.org/examples/pylab_examples/annotation_demo2.html" target="_blank">More examples for pyplot annotation</a>