# Lab 3 Assignment: 

### Please type your name here:
### Do not forget to change the filename with your name appended

In this lab please fill the indicated cells with your code and explainations, ***run*** everything (select `cell` in the menu, and click `Run all`), save the notebook with your name appended to the filename (for example, `Lab-03-assignment-shuhaocao.ipynb`), and upload it to Canvas.
<br><br>
This lab assignment contains three problems (that need to be turned in), and one extra problem (for you to try after lab). Even the fourth 
<br><br>
Read each problem carefully and answer them the best you can. You may type the code from Lecture 6 and 7 notebooks, please do not just copy/paste, rather use type and auto-complete by pressing Tab.

## Numpy Arrays
All the problems today are involving numpy arrays, please import `numpy` module first.

In [1]:
import numpy as np

## Review: vectorization
We can create an array using the following line:

In [18]:
arr1 = np.identity(3) + 1 + np.array(range(9)).reshape(3,3)
arr1

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [12]:
arr2 = np.array(range(9)).reshape(3,3) + np.array([[1],[5],[9]])
arr2

array([[ 1,  2,  3],
       [ 8,  9, 10],
       [15, 16, 17]])

In [10]:
def myfunc(a, b):
    # Return a-b if a>b, otherwise return a+b
    if a > b:
        return a - b
    else:
        return a + b

Now directly using this function on an array will give you error.

In [ ]:
myfunc(arr1, 2) 
# please delete this cell before submitting, it will give you error and is only for demonstration purpose

In [16]:
print(arr1,"\n")
zs = np.vectorize(myfunc)(arr1, 2)
print(zs)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]] 

[[4. 4. 1.]
 [2. 4. 4.]
 [5. 6. 8.]]


### Please complete Problem 1 and 2 for grading, Problem 3 is not graded but is very important

## Problem 1:
Create the following 3 by 3 matrix (multi-dimensional array) using a vectorized routine in the `numpy` module (either `float` or `int` is fine).
$$\begin{pmatrix} 
1   & 2  & 3 \\
5   & 6  & 7 \\
9  & 10  & 11 
\end{pmatrix}$$
*No* `for` loop nor any slicing operand `:` should be used.

In [ ]:
# code for Problem 1 here.


## Problem 2
Plot the following function g(x) for $x$ in $[-\pi,\pi]$ using `matplotlib` and `numpy` using exactly 1000 points in `np.linspace` function. Use the `math` module to import $\pi$. You can NOT import `math10.py` to do the plot for you.

$ g(x) =
  \begin{cases}
    x^{2}\sin\left(x^{3}\right)       & \quad \text{if } x \neq 0\\
    0 & \quad \text{if } x = 0\\
  \end{cases}$

You may check Lecture 4's annotated notebook in our class's [Github repo](https://github.com/scaomath/UCI-Math10-Winter19).

In [ ]:
# code for Problem 2 here.


## Problem 3 (not graded but very important)

You are given the following numpy array which contains stock prices for the last five days.  

In [8]:
import numpy as np
names = np.array(["AAPL", "GOOGL", "TSLA", "NVDA"])
# each row is a company
X = np.array([[135.55, 135.30, 136.26, 136.63, 137.20], 
              [838.97, 845.83, 851.24, 848.50, 850.01],
              [279.25, 270.67, 268.04, 278.88, 275.53],
              [108.24, 106.83, 107.14, 110.52, 110.64]])

### Problem 3 (a)
Produce an 1-dimensional **structured** array (with 4 elements) which will contain the company name and the **average** price of each stock **in the last 3 days**. 
<br><br>
**Hint**: use array slicing (i.e. taking `X[??,??]` where ?? are expressions that have `:` in them) and `np.apply_along_axis` and `np.mean`.

In [ ]:
# initialize this structured array
X_avg = np.array([("", 0.0), ("", 0.0), ("", 0.0), ("", 0.0)], 
                 dtype = [('name', 'S10'), ('avg_price', 'f8')])
print(X_avg['name'])
print(X_avg['avg_price'])
# your code here


### Problem 3 (b)

Say four new days of data are given to you as a numpy array called `Y` in the cell that follows. What would the shape of `Y` be? How would you make a new array for all the prices together? 
<br><br>
**Remark**: you can use slicing to set things too, like `X[0,:] = Z[3,:]` will make `X`'s row 0 (first row) be set to `Z`'s row 3 (4th row).

In [ ]:
Y = np.array([[139.,140.,141., 144.],
              [840., 841., 838., 836], 
              [276., 276., 277., 280], 
              [110., 108., 107., 109]])

In [20]:
# your code here